# Define workspace packages
packages:
  - apps/* # All applications in the apps directory
  - packages/* # All shared packages in the packages directory

# Shared dependency catalog for consistent versions across the monorepo
catalog:
  # Core Vue.js framework and routing
  vue: ^3.5.22
  vue-router: ^4.5.1,
  nuxt: ^4.1.3

  # TypeScript support
  typescript: ^5.9.3
  '@types/node': ^22.18.9

  # UI component libraries and styling utilities
  class-variance-authority: ^0.7.1 # CSS class variant management
  clsx: ^2.1.1 # Conditional CSS class utility
  lucide-vue-next: ^0.545.0 # Icon library for Vue
  reka-ui: ^2.5.1 # Headless UI components
  shadcn-nuxt: 2.3.1 # shadcn/ui components for Nuxt

  # Tailwind CSS and styling
  tailwind-merge: ^3.3.1 # Merge Tailwind classes intelligently
  tailwindcss: ^4.1.14 # Utility-first CSS framework
  tw-animate-css: ^1.4.0 # Tailwind animation utilities
  '@tailwindcss/vite': ^4.1.14 # Tailwind CSS Vite plugin

  # Vue composition utilities
  '@vueuse/core': ^13.9.0 # Vue composition utilities
