packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': ^4.1.14
  '@tanstack/vue-table': ^8.21.3
  '@types/node': ^22.18.9
  '@vee-validate/zod': ^4.15.1
  '@vueuse/core': 13.9.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  embla-carousel-vue: ^8.6.0
  lucide-vue-next: ^0.545.0
  nuxt: ^4.1.3
  reka-ui: 2.5.1
  shadcn-nuxt: 2.3.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.14
  turbo: ^2.5.8
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vaul-vue: ^0.4.1
  vee-validate: ^4.15.1
  vue: ^3.5.22
  vue-router: ^4.5.1
  vue-sonner: ^2.0.9
  zod: ^4.1.12

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - vue-demi
